### ISSUE TITLE
non op prob

### ISSUE THREAD

**Issue by owenraihan** [Xenophilicy/MaxEnchants#8]
non op can /enchant even I make it false

**Comment by Xenophilicy** [comment]
If you want to enable the permission so that players without the permission can't use it, set the permission to true. 

Here's an example of how that would look:

```yaml
  Permission:

    # Choose whether to require users to have permission to execute the command
    Enabled: true

    # This is the command's usage permission
    Node: "maxenchants.enchant"
```
